In [1]:
import pandas as pd

C:\Users\drudi\Anaconda3\envs\learn-env\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\drudi\Anaconda3\envs\learn-env\lib\site-packages\numpy\.libs\libopenblas.NOIJJG62EMASZI6NYURL6JBKM4EVBGM7.gfortran-win_amd64.dll
C:\Users\drudi\Anaconda3\envs\learn-env\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
  stacklevel=1)

In [15]:
traditional = pd.read_csv('Pain_Management.csv')
traditional.head()

,zip_code,min_medicare_pricing_for_new_patient,max_medicare_pricing_for_new_patient,mode_medicare_pricing_for_new_patient,min_copay_for_new_patient,max_copay_for_new_patient,mode_copay_for_new_patient,most_utilized_procedure_code_for_new_patient,min_medicare_pricing_for_established_patient,max_medicare_pricing_for_established_patient,mode_medicare_pricing_for_established_patient,min_copay_for_established_patient,max_copay_for_established_patient,mode_copay_for_established_patient,most_utilized_procedure_code_for_established_patient
0,210,38.248,171.272,136.376,9.562,42.818,34.094,99204,19.048,120.808,61.72,4.762,30.202,15.43,99213
1,211,38.248,171.272,136.376,9.562,42.818,34.094,99204,19.048,120.808,61.72,4.762,30.202,15.43,99213
2,212,38.248,171.272,136.376,9.562,42.818,34.094,99204,19.048,120.808,61.72,4.762,30.202,15.43,99213
3,213,38.248,171.272,136.376,9.562,42.818,34.094,99204,19.048,120.808,61.72,4.762,30.202,15.43,99213
4,214,38.248,171.272,136.376,9.562,42.818,34.094,99204,19.048,120.808,61.72,4.762,30.202,15.43,99213

In [16]:
traditional.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42954 entries, 0 to 42953
Data columns (total 15 columns):
 #   Column                                                Non-Null Count  Dtype
---  ------                                                --------------  -----
 0   zip_code                                              42954 non-null  int64
 1   min_medicare_pricing_for_new_patient                  42954 non-null  float64
 2   max_medicare_pricing_for_new_patient                  42954 non-null  float64
 3   mode_medicare_pricing_for_new_patient                 42954 non-null  float64
 4   min_copay_for_new_patient                             42954 non-null  float64
 5   max_copay_for_new_patient                             42954 non-null  float64
 6   mode_copay_for_new_patient                            42954 non-null  float64
 7   most_utilized_procedure_code_for_new_patient          42954 non-null  int64
 8   min_medicare_pricing_for_established_patient          42954 non-null  float64
 9   max_medicare_pricing_for_established_patient          42954 non-null  float64
 10  mode_medicare_pricing_for_established_patient         42954 non-null  float64
 11  min_copay_for_established_patient                     42954 non-null  float64
 12  max_copay_for_established_patient                     42954 non-null  float64
 13  mode_copay_for_established_patient                    42954 non-null  float64
 14  most_utilized_procedure_code_for_established_patient  42954 non-null  int64
dtypes: float64(12), int64(3)
memory usage: 4.9 MB

In [17]:
interventional = pd.read_csv('Interventional_Pain_Management.csv')
interventional.head()

,zip_code,min_medicare_pricing_for_new_patient,max_medicare_pricing_for_new_patient,mode_medicare_pricing_for_new_patient,min_copay_for_new_patient,max_copay_for_new_patient,mode_copay_for_new_patient,most_utilized_procedure_code_for_new_patient,min_medicare_pricing_for_established_patient,max_medicare_pricing_for_established_patient,mode_medicare_pricing_for_established_patient,min_copay_for_established_patient,max_copay_for_established_patient,mode_copay_for_established_patient,most_utilized_procedure_code_for_established_patient
0,210,38.248,171.272,136.376,9.562,42.818,34.094,99204,19.048,120.808,61.72,4.762,30.202,15.43,99213
1,211,38.248,171.272,136.376,9.562,42.818,34.094,99204,19.048,120.808,61.72,4.762,30.202,15.43,99213
2,212,38.248,171.272,136.376,9.562,42.818,34.094,99204,19.048,120.808,61.72,4.762,30.202,15.43,99213
3,213,38.248,171.272,136.376,9.562,42.818,34.094,99204,19.048,120.808,61.72,4.762,30.202,15.43,99213
4,214,38.248,171.272,136.376,9.562,42.818,34.094,99204,19.048,120.808,61.72,4.762,30.202,15.43,99213

In [18]:
interventional.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42954 entries, 0 to 42953
Data columns (total 15 columns):
 #   Column                                                Non-Null Count  Dtype
---  ------                                                --------------  -----
 0   zip_code                                              42954 non-null  int64
 1   min_medicare_pricing_for_new_patient                  42954 non-null  float64
 2   max_medicare_pricing_for_new_patient                  42954 non-null  float64
 3   mode_medicare_pricing_for_new_patient                 42954 non-null  float64
 4   min_copay_for_new_patient                             42954 non-null  float64
 5   max_copay_for_new_patient                             42954 non-null  float64
 6   mode_copay_for_new_patient                            42954 non-null  float64
 7   most_utilized_procedure_code_for_new_patient          42954 non-null  int64
 8   min_medicare_pricing_for_established_patient          42954 non-null  float64
 9   max_medicare_pricing_for_established_patient          42954 non-null  float64
 10  mode_medicare_pricing_for_established_patient         42954 non-null  float64
 11  min_copay_for_established_patient                     42954 non-null  float64
 12  max_copay_for_established_patient                     42954 non-null  float64
 13  mode_copay_for_established_patient                    42954 non-null  float64
 14  most_utilized_procedure_code_for_established_patient  42954 non-null  int64
dtypes: float64(12), int64(3)
memory usage: 4.9 MB

In [21]:
traditional.mode_copay_for_new_patient.value_counts(1)

32.174    0.047609
32.504    0.043791
32.190    0.034618
32.042    0.028728
33.032    0.026656
            ...
35.544    0.000512
33.436    0.000489
34.134    0.000396
34.138    0.000233
36.690    0.000116
Name: mode_copay_for_new_patient, Length: 97, dtype: float64

In [22]:
interventional.mode_copay_for_new_patient.value_counts(1)

32.174    0.047609
32.504    0.043791
32.190    0.034618
32.042    0.028728
33.032    0.026656
            ...
35.544    0.000512
33.436    0.000489
34.134    0.000396
34.138    0.000233
36.690    0.000116
Name: mode_copay_for_new_patient, Length: 97, dtype: float64

In [19]:
traditional.describe()

,zip_code,min_medicare_pricing_for_new_patient,max_medicare_pricing_for_new_patient,mode_medicare_pricing_for_new_patient,min_copay_for_new_patient,max_copay_for_new_patient,mode_copay_for_new_patient,most_utilized_procedure_code_for_new_patient,min_medicare_pricing_for_established_patient,max_medicare_pricing_for_established_patient,mode_medicare_pricing_for_established_patient,min_copay_for_established_patient,max_copay_for_established_patient,mode_copay_for_established_patient,most_utilized_procedure_code_for_established_patient
count,42954.000000,42954.000000,42954.000000,42954.000000,42954.000000,42954.000000,42954.000000,42954.0,42954.000000,42954.000000,42954.000000,42954.000000,42954.000000,42954.000000,42954.0
mean,49590.561694,36.577822,165.921357,131.916054,9.144456,41.480339,32.979014,99204.0,18.127904,116.868898,59.485500,4.531976,29.217225,14.871375,99213.0
std,27974.729869,2.478634,9.528802,7.714980,0.619658,2.382200,1.928745,0.0,1.330268,6.828314,3.650513,0.332567,1.707079,0.912628,0.0
min,210.000000,33.432000,153.976000,122.216000,8.358000,38.494000,30.554000,99204.0,16.584000,108.584000,55.048000,4.146000,27.146000,13.762000,99213.0
25%,26037.250000,34.736000,159.960000,127.072000,8.684000,39.990000,31.768000,99204.0,17.184000,112.224000,56.864000,4.296000,28.056000,14.216000,99213.0
50%,48812.500000,35.720000,163.584000,130.016000,8.930000,40.896000,32.504000,99204.0,17.632000,114.808000,58.224000,4.408000,28.702000,14.556000,99213.0
75%,73042.750000,37.464000,169.360000,134.568000,9.366000,42.340000,33.642000,99204.0,18.632000,118.840000,60.648000,4.658000,29.710000,15.162000,99213.0
max,99950.000000,46.256000,219.248000,173.464000,11.564000,54.812000,43.366000,99204.0,23.296000,153.568000,77.192000,5.824000,38.392000,19.298000,99213.0

In [20]:
interventional.describe()

,zip_code,min_medicare_pricing_for_new_patient,max_medicare_pricing_for_new_patient,mode_medicare_pricing_for_new_patient,min_copay_for_new_patient,max_copay_for_new_patient,mode_copay_for_new_patient,most_utilized_procedure_code_for_new_patient,min_medicare_pricing_for_established_patient,max_medicare_pricing_for_established_patient,mode_medicare_pricing_for_established_patient,min_copay_for_established_patient,max_copay_for_established_patient,mode_copay_for_established_patient,most_utilized_procedure_code_for_established_patient
count,42954.000000,42954.000000,42954.000000,42954.000000,42954.000000,42954.000000,42954.000000,42954.0,42954.000000,42954.000000,42954.000000,42954.000000,42954.000000,42954.000000,42954.0
mean,49590.561694,36.577822,165.921357,131.916054,9.144456,41.480339,32.979014,99204.0,18.127904,116.868898,59.485500,4.531976,29.217225,14.871375,99213.0
std,27974.729869,2.478634,9.528802,7.714980,0.619658,2.382200,1.928745,0.0,1.330268,6.828314,3.650513,0.332567,1.707079,0.912628,0.0
min,210.000000,33.432000,153.976000,122.216000,8.358000,38.494000,30.554000,99204.0,16.584000,108.584000,55.048000,4.146000,27.146000,13.762000,99213.0
25%,26037.250000,34.736000,159.960000,127.072000,8.684000,39.990000,31.768000,99204.0,17.184000,112.224000,56.864000,4.296000,28.056000,14.216000,99213.0
50%,48812.500000,35.720000,163.584000,130.016000,8.930000,40.896000,32.504000,99204.0,17.632000,114.808000,58.224000,4.408000,28.702000,14.556000,99213.0
75%,73042.750000,37.464000,169.360000,134.568000,9.366000,42.340000,33.642000,99204.0,18.632000,118.840000,60.648000,4.658000,29.710000,15.162000,99213.0
max,99950.000000,46.256000,219.248000,173.464000,11.564000,54.812000,43.366000,99204.0,23.296000,153.568000,77.192000,5.824000,38.392000,19.298000,99213.0

In [23]:
surgical = pd.read_csv('Surgical_Oncology.csv')
radiation = pd.read_csv('Radiation_Oncology.csv')

In [24]:
surgical.head()

,zip_code,min_medicare_pricing_for_new_patient,max_medicare_pricing_for_new_patient,mode_medicare_pricing_for_new_patient,min_copay_for_new_patient,max_copay_for_new_patient,mode_copay_for_new_patient,most_utilized_procedure_code_for_new_patient,min_medicare_pricing_for_established_patient,max_medicare_pricing_for_established_patient,mode_medicare_pricing_for_established_patient,min_copay_for_established_patient,max_copay_for_established_patient,mode_copay_for_established_patient,most_utilized_procedure_code_for_established_patient
0,210,38.248,171.272,171.272,9.562,42.818,42.818,99205,19.048,120.808,61.72,4.762,30.202,15.43,99213
1,211,38.248,171.272,171.272,9.562,42.818,42.818,99205,19.048,120.808,61.72,4.762,30.202,15.43,99213
2,212,38.248,171.272,171.272,9.562,42.818,42.818,99205,19.048,120.808,61.72,4.762,30.202,15.43,99213
3,213,38.248,171.272,171.272,9.562,42.818,42.818,99205,19.048,120.808,61.72,4.762,30.202,15.43,99213
4,214,38.248,171.272,171.272,9.562,42.818,42.818,99205,19.048,120.808,61.72,4.762,30.202,15.43,99213

In [25]:
radiation.head()

,zip_code,min_medicare_pricing_for_new_patient,max_medicare_pricing_for_new_patient,mode_medicare_pricing_for_new_patient,min_copay_for_new_patient,max_copay_for_new_patient,mode_copay_for_new_patient,most_utilized_procedure_code_for_new_patient,min_medicare_pricing_for_established_patient,max_medicare_pricing_for_established_patient,mode_medicare_pricing_for_established_patient,min_copay_for_established_patient,max_copay_for_established_patient,mode_copay_for_established_patient,most_utilized_procedure_code_for_established_patient
0,210,38.248,171.272,171.272,9.562,42.818,42.818,99205,19.048,120.808,61.72,4.762,30.202,15.43,99213
1,211,38.248,171.272,171.272,9.562,42.818,42.818,99205,19.048,120.808,61.72,4.762,30.202,15.43,99213
2,212,38.248,171.272,171.272,9.562,42.818,42.818,99205,19.048,120.808,61.72,4.762,30.202,15.43,99213
3,213,38.248,171.272,171.272,9.562,42.818,42.818,99205,19.048,120.808,61.72,4.762,30.202,15.43,99213
4,214,38.248,171.272,171.272,9.562,42.818,42.818,99205,19.048,120.808,61.72,4.762,30.202,15.43,99213

In [26]:
surgical.describe()

,zip_code,min_medicare_pricing_for_new_patient,max_medicare_pricing_for_new_patient,mode_medicare_pricing_for_new_patient,min_copay_for_new_patient,max_copay_for_new_patient,mode_copay_for_new_patient,most_utilized_procedure_code_for_new_patient,min_medicare_pricing_for_established_patient,max_medicare_pricing_for_established_patient,mode_medicare_pricing_for_established_patient,min_copay_for_established_patient,max_copay_for_established_patient,mode_copay_for_established_patient,most_utilized_procedure_code_for_established_patient
count,42954.000000,42954.000000,42954.000000,42954.000000,42954.000000,42954.000000,42954.000000,42954.0,42954.000000,42954.000000,42954.000000,42954.000000,42954.000000,42954.000000,42954.0
mean,49590.561694,36.577822,165.921357,165.921357,9.144456,41.480339,41.480339,99205.0,18.127904,116.868898,59.485500,4.531976,29.217225,14.871375,99213.0
std,27974.729869,2.478634,9.528802,9.528802,0.619658,2.382200,2.382200,0.0,1.330268,6.828314,3.650513,0.332567,1.707079,0.912628,0.0
min,210.000000,33.432000,153.976000,153.976000,8.358000,38.494000,38.494000,99205.0,16.584000,108.584000,55.048000,4.146000,27.146000,13.762000,99213.0
25%,26037.250000,34.736000,159.960000,159.960000,8.684000,39.990000,39.990000,99205.0,17.184000,112.224000,56.864000,4.296000,28.056000,14.216000,99213.0
50%,48812.500000,35.720000,163.584000,163.584000,8.930000,40.896000,40.896000,99205.0,17.632000,114.808000,58.224000,4.408000,28.702000,14.556000,99213.0
75%,73042.750000,37.464000,169.360000,169.360000,9.366000,42.340000,42.340000,99205.0,18.632000,118.840000,60.648000,4.658000,29.710000,15.162000,99213.0
max,99950.000000,46.256000,219.248000,219.248000,11.564000,54.812000,54.812000,99205.0,23.296000,153.568000,77.192000,5.824000,38.392000,19.298000,99213.0

In [27]:
df = pd.read_csv('Skilled_Nursing_Facility_Quality.csv')

In [28]:
df.head()

,CMS Certification Number (CCN),Measure Code,Score,Footnote,Start Date,End Date
0,NATION,S_001_03_NATL_RATE,99.10,NaN,01/01/2019,12/31/2019
1,NATION,S_004_01_PPR_PD_NAT_UNADJUST_AVG,7.67,NaN,10/01/2017,09/30/2019
2,NATION,S_004_01_PPR_PD_N_BETTER_NAT,13.00,NaN,10/01/2017,09/30/2019
3,NATION,S_004_01_PPR_PD_N_NO_DIFF_NAT,15415.00,NaN,10/01/2017,09/30/2019
4,NATION,S_004_01_PPR_PD_N_TOO_SMALL,1482.00,NaN,10/01/2017,09/30/2019